spring:
  application:
    name: sample-bank
    datasource:
      url: jdbc:h2:mem:BANKDB;INIT=CREATE SCHEMA IF NOT EXISTS BANKDB;
      driverClass: org.h2.driver
      username: sa
      password:
      dialect: org.hibernate.dialect.H2Dialect
  jpa:
    hibernate:
      ddl-auto: create-drop
  h2:
    console:
      enabled: true

server:
  port: 26110      
