CREATE TABLE IF NOT EXISTS ACCOUNTS
(
	NAME VARCHAR2(255),
	ADDRESS VARCHAR2(2000),
	ACCOUNT_NUMBER INT,
	CREATED_TIME TIMESTAMP,
	BALANCE INT
);

CREATE TABLE IF NOT EXISTS BENEFICIARIES
(
	ID INT,
	ACCOUNT_NUMBER INT,
	BENEFICIARY_ACC_NUMBER INT,
	CREATED_TIME TIMESTAMP
);

CREATE TABLE IF NOT EXISTS TRANSACTIONS
(
	ID INT,
	FROM_ACCOUNT INT,
	TO_ACCOUNT INT,
	AMOUNT INT,
	IS_COMPLETE INT,
	CREATED_TM TIMESTAMP,
	COMPLETED_TM TIMESTAMP
);

CREATE SEQUENCE IF NOT EXISTS CUSTOMERS_SEQ INCREMENT BY 1 MINVALUE 100 MAXVALUE 9999999999999 CACHE 20;
CREATE SEQUENCE IF NOT EXISTS ACCOUNTS_SEQ  INCREMENT BY 1 MINVALUE 100 MAXVALUE 9999999999999 NOCYCLE CACHE 20;
CREATE SEQUENCE IF NOT EXISTS BENEFICIARIES_SEQ INCREMENT BY 1 MINVALUE 100 MAXVALUE 9999999999999 NOCYCLE CACHE 20;
CREATE SEQUENCE IF NOT EXISTS TRANSACTIONS_SEQ  INCREMENT BY 1 MINVALUE 100 MAXVALUE 9999999999999 NOCYCLE CACHE 20;

INSERT INTO ACCOUNTS(NAME,ADDRESS,ACCOUNT_NUMBER,CREATED_TIME,BALANCE) VALUES ('John', 'SF', 135, CURRENT_TIMESTAMP(), 800);
